Messaging: Resolve missing symbol
packages/apps/Messaging/src/com/android/messaging/ui/ContactIconView.java:60: error: cannot find symbol
        final int iconSizeId = a.getInt(R.styleable.ContactIconView_iconSize, 0);
                                                   ^
symbol:   variable ContactIconView_iconSize
location: class styleable

Change-Id: I83b0d869a02971c43eb1aa8b80d418832900471c